version: '3.9'

services:
  pgadmin_dev:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - pgadmin_dev:/root/.pgadmin

  db_dev:
    container_name: db_dev
    image: postgres:13.4-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env.dev
    volumes:
      - postgres_dev:/var/lib/postgresql/data

  nginx_dev:
    container_name: nginx_dev
    image: nginx:stable-alpine
    volumes:
      - ./nginx/ngin.dev.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - pgadmin_dev
      - db_dev

volumes:
  postgres_dev:
  pgadmin_dev:
