version: '3.9'

services:
  backend:
    command: yarn run dev
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend/src:/app/backend/src

  frontend:
    command: yarn run dev
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/frontend/src

  db:
    env_file:
      - ./backend/.env.dev