version: '3.9'

services:
  be:
    container_name: be
    build: ./backend
    restart: unless-stopped
    command: yarn prod
    env_file:
      - .env
    depends_on:
      - db

  fe:
    container_name: fe
    build: ./frontend
    restart: unless-stopped
    command: yarn prod
    env_file:
      - .env
    depends_on:
      - be

  email:
    container_name: email
    build: ./email_service
    command: uvicorn main:app --root-path /email --reload --workers 1 --host 0.0.0.0 --port 4001
    env_file: .env

  db:
    container_name: db
    image: postgres:13.4-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fe
      - be
      - email
      - db

volumes:
  postgres:
