version: '3.9'

services:
  backend:
    command: yarn run dev
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/src:/app/backend/src

  frontend:
    command: yarn run dev
    env_file:
      - ./.env.dev
    volumes:
      - ./frontend/src:/app/frontend/src

  db:
    env_file:
      - ./.env.dev
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: