version: '3.9'

services:
  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    command: yarn dev
    env_file:
      - ./.env.dev
    volumes:
      - media_volume:/app/backend/uploads
      - ./backend/src:/app/backend/src
    depends_on:
      - db_dev

  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    command: yarn dev
    stdin_open: true
    tty: true
    env_file:
      - ./.env.dev
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public

  pgadmin_dev:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes:
      - pgadmin_dev:/root/.pgadmin

  db_dev:
    container_name: db_dev
    image: postgres:13.4-alpine
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes:
      - postgres_dev:/var/lib/postgresql/data

  admin_client_dev:
    container_name: admin_client_dev
    build: ./admin/client
    restart: unless-stopped
    command: yarn start
    stdin_open: true
    tty: true
    env_file:
      - ./.env.dev
    volumes:
      - ./admin/client/src:/app/admin/client/src
      - ./admin/client/public:/app/admin/client/public

  admin_translations_dev:
    container_name: admin_translations_dev
    build: ./admin/translations
    restart: unless-stopped
    command: yarn dev
    env_file:
      - ./.env.dev
    volumes:
      - translations_dev:/app/admin/translations/media
      - ./admin/translations/src:/app/admin/translations/src

  nginx_dev:
    image: nginx:stable-alpine
    container_name: nginx_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
      - media_volume:/app/backend/uploads
      - translations_dev:/app/admin/translations/media
    depends_on:
      - frontend
      - backend
      - db_dev
      - pgadmin_dev
      - admin_translations_dev
      - admin_client_dev

volumes:
  postgres_dev:
  pgadmin_dev:
  media_volume:
  translations_dev:
