default:
  type: 'postgres'
  port: 5432
  host: 'db_dev'
  database: 'house_rent_dev'
  username: 'house_rent_dev'
  password: 'house_rent_dev'
  logging: true
  migrations: [ 'src/migration/*.ts' ]
  cli:
    migrationsDir: 'src/migration'